### ISSUE TITLE
About calibration models,fisheye cameras and GNSS

### ISSUE THREAD

**Issue by FPSychotic** [xuankuzcr/our_sensor_suit#1]
Thanks by share your project and knowledge.

- Can I ask you if your software supports Rational Polinomial model as calibration model?  As Equidistant it fits better to fisheye cameras than the most common ROS plumb_bob model.

- Will your software take advantage of a camera with much more FOV than the lidar (Avia)? Is instead is better try find a close FOV  fit , normally fish eye is better for VIO but maybe it is not the case .

- Is it possible use GNSS to georeference the pointcloud? Or it is only to take the ground true.  
Can be georeferenced and make normals (structured pointcloud) to can generate meshes easier and make them compatible with software as Reality Capture ?would be great, not sure if that is possible already.

Best of lucks.

**Comment by xuankuzcr** [comment]
1. Our camera model depends on the vikit library, which also supports common projection and distortion models of fish eye cameras. However, we use Pinhole + Radtan by default.
2. It is better to use LiDAR and camera with FoV approach. As for fish eye, you'd better use 360 degree mechanical LiDAR. The next version of FAST-LIVO can work on datasets with large fov gaps without losing camera information.
3. Sorry, I know little about GNSS, and I only use it for ground truth.

**Comment by FPSychotic** [comment]
Thank you so much by your helpful answer, best of lucks.
